http://stackoverflow.com/questions/22775371/how-to-iterate-through-a-numpy-array-and-select-neighboring-cells

In [8]:
import numpy as np

explore_map = np.array([[0,0,0,0,0,0],[0,1,1,0,0,0],[0,1,0,1,0,0],[0,0,0,0,1,0],[0,0,0,0,1,0],[0,0,0,0,0,0]])
store_map = np.array([[0,0,0,0,0,0],[0,0,0,1,0,0],[0,0,0,0,1,0],[0,1,0,0,0,0],[0,1,0,0,0,0],[0,0,0,0,0,0]])
print(explore_map)
print("")
print(store_map)

[[0 0 0 0 0 0]
 [0 1 1 0 0 0]
 [0 1 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 0]]

[[0 0 0 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 1 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 0 0 0 0]]


In [23]:
neighbours = [(-1,-1), (-1,0), (-1,1), (0,1), (1,1), (1,0), (1,-1), (0,-1)]
mask = np.zeros_like(z, dtype = bool)
stack = [(1,1)] # push start coordinate on stack
mask

while stack:
    x, y = stack.pop()
    mask[x, y] = True
    for dx, dy in neighbours:
        nx, ny = x + dx, y + dy
        if (0 <= nx < z.shape[0] and 0 <= ny < z.shape[1] 
            and not mask[nx, ny] and abs(z[nx, ny] - z[x, y]) < 1):
            stack.append((nx, ny))
mask

array([[ True,  True,  True, False, False, False],
       [ True,  True, False,  True, False, False],
       [ True, False, False, False,  True,  True]], dtype=bool)