Shift elements within a given range around an index location to cloe gaps around the location  

In [6]:
import numpy as np
from scipy.ndimage.interpolation import shift
from collections import deque, namedtuple

In [7]:
Location = namedtuple("Location", ("x", "y"))

In [8]:
neighbours = [(-1, -1), (-1, 0), (-1, 1), (0, 1), (1, 1), (1, 0),
                      (1, -1), (0, -1)]

In [9]:
bot_map = np.array(
      [[ 0,  1,  0,  0,  0, 0,  1,  0,  0,  0],
       [ 0.,  0.,  0.,  0.,  0., 0.,  1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  1.,  0., 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0., 0.,  1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  2., 0.,  4.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0., 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0., 0.,  1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  1.,  0., 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0., 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0., 0.,  1.,  0.,  0.,  0.]])

In [10]:
tail = Location(3,4)       

In [14]:
for ny, nx in neighbours:
    # first evaulate the x direction (-/+)
    x, y = tail.x, tail.y    

In [16]:
# near_bots = self.bot_map[y, x + nx: x + nx + (nx * BOT_DEFAULTS["recruit_range"]): nx]
near_bots = bot_map[y, x + nx: x + nx + (nx * 5): nx]
near_bots

array([], dtype=float64)

In [33]:
a = bot_map[y, x+nx: x+(nx*sense_range): nx]
a

/home/hemma/.local/lib/python3.5/site-packages/ipykernel/__main__.py:1: VisibleDeprecationWarning: converting an array with ndim > 0 to an index will result in an error in the future
  if __name__ == '__main__':


array([[0, 0, 0, 1]])

Indices in array element 0 (which is a list!) where the current value does not equal the next (left to right) i.e. there is a bot at the next location!

In [34]:
c = np.where(a[0][:-1]!=a[0][1:])
c

(array([2]),)

...add 1 to each value to get the next bot location.

In [35]:
d = c[0]+1
d

array([3])

Check if the occupied location is occupied by an explorer bot and hence a potential recruit.
n.b. explorer map should have current relay chain members removed.

In [36]:
if near_bots.any():
print(near_bots)
next_cell_different = np.where(
    near_bots[0][:-1] != near_bots[0][1:])
# add 1 to make these values useful
next_cell_different += 1
# is the first near bot on the explorer - relay chain map?
first_bot = near_bot[0]
# generate a map of explorers - those already in relay chains
near_bots_map = np.ma.make_mask(self.explore_mode_map) * 1

for existing_relay in Relay_Chain.relay_chain_maps:
    near_bots_map -= np.ma.make_mask(existing_relay) * 1

if near_bot_map[y, x + nx + nx * next_cell_different[0]]:
    print(
    near_bot_map[y, x + nx + nx * next_cell_different[0]])

near_explorer_bots = self.bot_map[y, x + nx: x + nx + (
nx * BOT_DEFAULTS["recruit_range"]): nx]
next_cell_different = np.where(
    near_explorer_bots[0][:-1] != near_explorer_bots[0][1:])
next_cell_different += 1

try:
    last_bot = near_explorer_bots[1]
except IndexError:
    last_bot = len(near_explorer_bots)

# shuffle bots to close gap

if nx == 1:
    self.bot_map[y][x + nx: x + nx + last_bot * nx] = shift(
        self.bot_map[y][x + nx: x + nx + last_bot],
        next_cell_different[0] * nx)

elif nx == -1:
    self.bot_map[y][x + nx + last_bot * nx:x + nx] = shift(
        self.bot_map[y][x + nx + last_bot * nx:x + nx],
        next_cell_different[0] * nx)

3

In [37]:
if explorer_bot_map[y, x + nx + nx*(e)]:
    print(explorer_bot_map[y, x + nx + nx*(e)])

[1]


There is! 
Now find where the line of potential recruits within the sense range stops by finding the second point at which the value on the explorer bot map changes from occupied to unoccupied.
(i.e.Repeat the operation used for the bot_map.)

In [38]:
g = explorer_bot_map[y,x+nx:x+(nx*sense_range):nx]
g

/home/hemma/.local/lib/python3.5/site-packages/ipykernel/__main__.py:1: VisibleDeprecationWarning: converting an array with ndim > 0 to an index will result in an error in the future
  if __name__ == '__main__':


array([[0, 0, 0, 1]])

In [39]:
h = np.where(g[0][:-1]!=g[0][1:])
h

(array([2]),)

And, like before add 1 to each value

In [40]:
i = h[0]+1
i

array([3])

In [41]:
j = i[0]
j

3

Does a second point exist where the value changes from occupied back to unoccupied? If so, store this value. If not, 

In [42]:
try:
    k = e[0][1]
except IndexError:
    k = len(g[0])
k

4

In [75]:
y=2
x1=1
x2=2
if nx == 1:
    bot_map[y][x1+nx:x2+k] = shift(bot_map[y][x1+nx:x2+k],2)
    
elif nx == -1:
    bot_map[y][x2+(k*nx): x1+nx] = shift(bot_map[y][x2+(k*nx): x1+nx],2)


In [74]:
bot_map = np.array([[0,0,0,0,1,1,1,0,0,1,1,0], 
                    [0,0,0,0,1,1,1,0,0,0,1,0], 
                    [0,0,0,0,1,1,1,0,0,0,1,0], 
                    [0,0,0,0,1,1,1,0,0,1,1,0]])

to shift a section of a row

In [53]:
from scipy.ndimage.interpolation import shift
# print(bot_map)
# print(bot_map[1,:][1:4])
# bot_map[0,:][1:4] = shift(bot_map[0,:][1:4], 3)
# bot_map
print(bot_map)
bot_map[1][4:6] = shift(bot_map[1][4:6],2)
bot_map

[[0 0 0 0 1 1 1 0 0 1 1 0]
 [0 0 0 0 1 1 1 0 0 0 1 0]
 [0 0 0 0 1 1 4 0 0 0 1 0]
 [0 0 0 0 1 1 1 0 0 1 1 0]]


array([[0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 1, 4, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0]])

to shift a section of a column

In [40]:
print(bot_map[:,-3][0:3])
bot_map[:,-3][0:3] = shift(bot_map[:,-3][0:3],1)
bot_map

[0 1 0]


array([[0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0]])

In [21]:
shift(p,3)

NameError: name 'p' is not defined