In [52]:
import numpy as np    

In [53]:
A = np.array([[1,2,3],[4,5,6]])

B = np.array([[1,2,4],[3,4,5]])

C = np.where(A==3)

B[C] = 0

B



#                 np.clip(self.food_map -
#                         (np.ma.make_mask(np.where(self.charge_map == chargePerTimetep)*1),
#                              chargePerTimetep)
#                          * BOT_DEFAULTS["EinPerFeed"]),
#                         0, float("inf"),
#                         self.food_map)

#             #increment charge map by one at locations with bot and food

#             #self.charge_map +=

#             self.charge_map += np.clip(
#                 np.multiply(
#                     np.ma.make_mask(self.bot_map) * 1,
#                     np.ma.make_mask(self.food_map) * 1,
#                 )
#                 + np.ma.make_mask(self.charge_map) * 1,
#                 0, 1)


array([[1, 2, 0],
       [3, 4, 5]])

In [54]:
D = np.where(A & (B ==0))

In [55]:
D

(array([0]), array([2]))

In [56]:
A[D]=14
A

array([[ 1,  2, 14],
       [ 4,  5,  6]])

In [57]:
A[D]+= 4
A

array([[ 1,  2, 18],
       [ 4,  5,  6]])

In [58]:
A[0,2]=3


In [59]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
A[(0,2),(1,1)]=12
A

IndexError: index 2 is out of bounds for axis 0 with size 2

In [62]:
A[0,2]=4
A

array([[ 1, 12,  4],
       [ 4, 12,  6]])