In [13]:
import numpy as np
a = np.full((5,4,4,3), 2)
a = np.random.rand(5,4,4,3)
print(a)

[[[[0.36603074 0.69407734 0.131492  ]
   [0.41079207 0.3732655  0.74348481]
   [0.85954666 0.62209435 0.62010705]
   [0.78373453 0.97883471 0.73350398]]

  [[0.52520293 0.11767524 0.53902967]
   [0.10247374 0.8813486  0.94281437]
   [0.00874418 0.54571344 0.96285735]
   [0.90987487 0.97011896 0.40195957]]

  [[0.13976652 0.84477258 0.55031301]
   [0.07285818 0.36571796 0.94562272]
   [0.82066511 0.06622044 0.92862727]
   [0.88972365 0.90129555 0.23786974]]

  [[0.16991914 0.67301997 0.54453224]
   [0.23183112 0.74243467 0.94737713]
   [0.72321101 0.89526206 0.36295311]
   [0.73971994 0.28433763 0.84086439]]]


 [[[0.17982232 0.67948766 0.17246061]
   [0.56791025 0.04626544 0.2499742 ]
   [0.9239846  0.97594297 0.01141993]
   [0.32026265 0.33216232 0.35346128]]

  [[0.90493285 0.8296554  0.7666239 ]
   [0.19489988 0.25794944 0.74751294]
   [0.93410986 0.24147292 0.08251548]
   [0.04865228 0.40756037 0.05673129]]

  [[0.63967917 0.92062184 0.74631207]
   [0.32716634 0.75164147 0.20522201

In [14]:
b = a.reshape(a.shape[0], 4 * 4 * 3)
print(b.shape)
print(b)

(5, 48)
[[0.36603074 0.69407734 0.131492   0.41079207 0.3732655  0.74348481
  0.85954666 0.62209435 0.62010705 0.78373453 0.97883471 0.73350398
  0.52520293 0.11767524 0.53902967 0.10247374 0.8813486  0.94281437
  0.00874418 0.54571344 0.96285735 0.90987487 0.97011896 0.40195957
  0.13976652 0.84477258 0.55031301 0.07285818 0.36571796 0.94562272
  0.82066511 0.06622044 0.92862727 0.88972365 0.90129555 0.23786974
  0.16991914 0.67301997 0.54453224 0.23183112 0.74243467 0.94737713
  0.72321101 0.89526206 0.36295311 0.73971994 0.28433763 0.84086439]
 [0.17982232 0.67948766 0.17246061 0.56791025 0.04626544 0.2499742
  0.9239846  0.97594297 0.01141993 0.32026265 0.33216232 0.35346128
  0.90493285 0.8296554  0.7666239  0.19489988 0.25794944 0.74751294
  0.93410986 0.24147292 0.08251548 0.04865228 0.40756037 0.05673129
  0.63967917 0.92062184 0.74631207 0.32716634 0.75164147 0.20522201
  0.70014467 0.46666097 0.60348873 0.35401493 0.93704347 0.03680028
  0.60439361 0.18929531 0.92023929 0.101