# Knapsack
https://dougfenstermacher.com/blog/combinatorial-optimization

Given a set of items, each with a weight and a value, determine the number of each item to include in a collection so that the total weight is less than or equal to a given limit and the total value is as large as possible.

0–1 Knapsack problem. For each item, there are two possibilities:

Include the current item in the subset 
Exclude the current item from the subset 

In [102]:
import numpy as np
import random

In [103]:
W = 10
v_ = [10, 40, 30, 50]
w_ = [5, 4, 6, 3]


def knapsack(v_, w_, W): 
    """
    v_ = values
    w_ = weights
    W = max weight
    """
    n = len(v_)
    
    V = np.zeros((n+1,W+1))
    keep = np.zeros((n+1,W+1))
    
#     for w in range(W+1):
#         V[0,w] = 0

    for i in range(1, n+1):
        for w in range(W+1):
            #print(i,w)
            
            # take item
            if w >= w_[i-1] and (v_[i-1] + V[i-1, w-w_[i-1]] > V[i-1,w]):
            
                V[i,w] = v_[i-1] + V[i-1, w-w_[i-1]]
                
                keep[i,w] = 1
                
            # leave item
            else:
                V[i,w] = V[i-1,w]

        
        
    return V, keep
        
    
    

In [13]:
V, keep = knapsack(v_, w_, W)
print(V)
print(keep)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. 10. 10. 10. 10. 10. 10.]
 [ 0.  0.  0.  0. 40. 40. 40. 40. 40. 50. 50.]
 [ 0.  0.  0.  0. 40. 40. 40. 40. 40. 50. 70.]
 [ 0.  0.  0. 50. 50. 50. 50. 90. 90. 90. 90.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [14]:
T = []

n = len(v_)

K = W

for i in range(n, -1, -1):
    if keep[i,K]==1:
        print(w_[i-1])
        K = K-w_[i-1]
        print(K)
        T.append(i)
        
print(T)

3
7
4
3
[4, 2]


In [15]:
v_ = [60, 100, 120]
w_ = [10, 20, 30]
W = 50

# Subset 

(subset sums https://dougfenstermacher.com/blog/combinatorial-optimization)

Subset with maximum value without exceeding limit (special case of Knapsack)

In [220]:
def subset_max(data, limit):
    """
    Returns all subsets where value does not exceed limit 
    """
    
    cache = [None for _ in range(limit+1)]
    cache[0] = []
    
    for d in data:
        for i in range(limit - d, -1, -1):

            if cache[i] is not None:
                cache[i + d] = cache[i] + [d]
        print()
        
    return(cache)
                
                

In [240]:
data = [1, 2, 3, 4, 13, 3, 25, 20]

solution = subset_max(data, 50)

print(solution)

print('\nSubset that gives greatest total without exceeding limit', solution[-1])









[[], [1], [2], [3], [1, 3], [2, 3], [3, 3], [4, 3], [1, 4, 3], [2, 4, 3], [3, 4, 3], [1, 3, 4, 3], [2, 3, 4, 3], [1, 2, 3, 4, 3], [1, 13], [2, 13], [13, 3], [1, 13, 3], [2, 13, 3], [3, 13, 3], [20], [1, 20], [2, 20], [3, 20], [1, 3, 20], [2, 3, 20], [3, 3, 20], [4, 3, 20], [1, 4, 3, 20], [2, 4, 3, 20], [3, 4, 3, 20], [1, 3, 4, 3, 20], [2, 3, 4, 3, 20], [1, 2, 3, 4, 3, 20], [1, 13, 20], [2, 13, 20], [13, 3, 20], [1, 13, 3, 20], [2, 13, 3, 20], [3, 13, 3, 20], [4, 13, 3, 20], [1, 4, 13, 3, 20], [2, 4, 13, 3, 20], [3, 4, 13, 3, 20], [1, 3, 4, 13, 3, 20], [25, 20], [1, 25, 20], [2, 25, 20], [3, 25, 20], [1, 3, 25, 20], [2, 3, 25, 20]]

Subset that gives greatest total without exceeding limit [2, 3, 25, 20]


In [237]:
subset_max(data, 20)[-1]

[20]

Todo: Brute force solution

# Subset sum 
https://www.geeksforgeeks.org/subset-sum-problem-dp-25/

https://www.techiedelight.com/subset-sum-problem/

Given a set of non-negative integers, and a value sum, determine if there is a subset of the given set with sum equal to given sum. 

## Method 1: Recursive function 

In [20]:
# A recursive solution for subset sum
# problem
 
# Returns true if there is a subset
# of set[] with sun equal to given sum
 
 
def isSubsetSum(set_, n, sum_):
 
    # Base Cases
    if (sum_ == 0):
        return True
    if (n == 0):
        return False
 
    # If last element is greater than
    # sum, then ignore it
    if (set_[n - 1] > sum_):
        return isSubsetSum(set_, n - 1, sum_)
 
    # else, check if sum can be obtained
    # by any of the following
    # (a) including the last element
    # (b) excluding the last element
    return isSubsetSum(
        set_, n-1, sum_) or isSubsetSum(
        set_, n-1, sum_-set_[n-1])
 
 
# Driver code
set_ = [3, 34, 4, 12, 5, 2]

sum_ = 9

n = len(set_)

if (isSubsetSum(set_, n, sum_) == True):
    print("Found a subset with given sum")
else:
    print("No subset with given sum")

Found a subset with given sum


## Method 2: Dynamic programming

In [23]:
# A Dynamic Programming solution for subset
# sum problem Returns true if there is a subset of
# set[] with sun equal to given sum
 
# Returns true if there is a subset of set[]
# with sum equal to given sum
def isSubsetSum(set_, n, sum_):
    """
    # The value of subset[i][j] will be true if there is a subset of set[0..j-1] with sum equal to i
    """
     
    # create array 
    subset =([[False for j in range(sum_ + 1)]for i in range(n + 1)])
    
    keep = ([[False for j in range(sum_ + 1)]for i in range(n + 1)])
    
    # Base cases:
    
    # If sum is 0, then subset[i][j] is true
    for i in range(n + 1):
        subset[i][0] = True
         
    # If sum is not 0 and n is 0 (empty set), then subset[i][j] is false
    for i in range(1, sum_ + 1):
         subset[0][i]= False
             
    # Fill the subset table in bottom up manner
    for i in range(1, n + 1):
        for j in range(1, sum_ + 1):
            
            # If current sum < current element, leave element (too big)
            # Subset[i][j] takes value of previous element
            if j<set_[i-1]:
                #print(i, j, set[i-1], subset[i-1][j])
                subset[i][j] = subset[i-1][j]
                
            
            # Otherwise 
            if j>= set_[i-1]:
                subset[i][j] = (subset[i-1][j] or           # Leave element 
                                subset[i - 1][j-set_[i-1]])  # Take element (remaining sum can be found with remaining subset)  once element taken)
                
                if subset[i - 1][j-set_[i-1]]:       # element taken               
                                 keep[i][j]=True
     
    # uncomment this code to print table
    for i in range(n + 1):
        for j in range(sum_ + 1):
            print (int(subset[i][j]), end =" ")
        print()
        
    # return the final (bottom-right) element
    # return subset[n][sum] 
    
    # return the array
    return subset, keep
         
# Driver code
if __name__=='__main__':
    
    set_ = [3, 1, 5, 2]
    
    sum_ = 10
    
    n = len(set_)
    
    subset, keep = isSubsetSum(set_, n, sum_)
    
    if (subset[n][sum_] == True):
        print("Found a subset with given sum")
    else:
        print("No subset with given sum")
    
    
#     if (isSubsetSum(set, n, sum) == True):
#         print("Found a subset with given sum")
#     else:
#         print("No subset with given sum")



         
# This code is contributed by
# sahil shelangia.

1 0 0 0 0 0 0 0 0 0 0 
1 0 0 1 0 0 0 0 0 0 0 
1 1 0 1 1 0 0 0 0 0 0 
1 1 0 1 1 1 1 0 1 1 0 
1 1 1 1 1 1 1 1 1 1 1 
Found a subset with given sum


In [24]:
T = []

K = sum_

for i in range(n, -1, -1):
    if keep[i][K]==1:
        print(set_[i-1])
        K = K-set_[i-1]
        print(K)
        T.append(set_[i-1])
        
print(T)

2
8
5
3
3
0
[2, 5, 3]


# Perfect Sum Problem (Print all subsets with given sum)
Given an array of integers and a sum, the task is to print all subsets of the given array with a sum equal to a given sum.

https://kalkicode.com/print-subsets-given-sum

In [34]:
#Python Program 
#Print all subsets with given sum
class MyArray:

  def subsets(self, total , inputs, result, size, index, sum_):
    
    # stopping condition: index out of range or cumulative sum exceeds total
    # do not return subset
    if(index > total  or  sum_ > total ):
      return

    # stopping condition: sum equals total
    if(sum_ == total):
        
        # print all sub, elements can be used more than once
        # print(result[:index])
        
        # print subset, elements can only be used once
        if sum(set(result[:index]))==total:
            print(result[:index])    
    
    
    # recur if neither stopping condition reached
    else :
      for element in inputs:
        
        #Get result elements
        result[index] = element

        #Recursive call
        self.subsets(total, inputs, result, size, index+1, sum_+element)

        
def main():

  obj = MyArray()
  #list elements
  inputs =[1,2,3,4,5,6]

  #Get the size of array elements
  size=len(inputs)

  total=6 #perfect sum

  #Auxiliary space which is store the result
  result=[0]*size

  #show all subset
  obj.subsets(total,inputs,result,size,0,0)
 
if __name__ =="__main__":
  main()

[1, 2, 3]
[1, 3, 2]
[1, 5]
[2, 1, 3]
[2, 3, 1]
[2, 4]
[3, 1, 2]
[3, 2, 1]
[4, 2]
[5, 1]
[6]


# Task Assignment

A number of agents and a number of tasks. 

Any agent can be assigned to perform any task, incurring some cost that may vary depending on the agent-task assignment. 

It is required to perform all tasks by assigning exactly one agent to each task and exactly one task to each agent in such a way that the total cost of the assignment is minimized.

The assignment problem comes up often in everyday life, such as optimally determining which athletic trainer to assign to each athlete in a queue, determining how to assign technicians to support tickets based on their skillset and location, or determining the optimal way to assign salesperson to potential companies.

The scipy function `linear_sum_assignment` function can also solve a generalization of the classic assignment problem where the cost matrix is rectangular. If it has more rows than columns, then not every row needs to be assigned to a column, and vice versa.

In [140]:
def build_cost_matrix(cost_func):
    return np.array([[cost_func(worker, task) for task in tasks.values()] for worker in workers])


def cost(worker, task):
    profit = (worker['rate'] * task) - worker['pay'] # picking rate * flower value - worker pay
    return 0 - abs(profit)                           # output mimimises cost function, so convert to -ve


workers = [{'pay': 20, 'rate': 300}, {'pay': 10.5, 'rate': 200}, {'pay': 15, 'rate': 150}, {'pay': 6.5, 'rate': 100}, {'pay': 17.5, 'rate': 200}]
tasks = {'orchid':10, 'daisy':2.25, 'daffodil':1.70, 'dandelion':0.001, 'grass':0.0001, 'tulip':0.0001}


flower_labels = flowers.keys()
flower_assignments = flowers.values()

In [141]:
from scipy.optimize import linear_sum_assignment

cost_matrix = build_cost_matrix(cost)

print('cost matrix \n', np.matrix(cost_matrix))

workerID, taskID = linear_sum_assignment(cost_matrix)

assign_matrix = np.zeros(cost_matrix.shape)

for w, t in zip(workerID, taskID):
    assign_matrix[w, t] = 1
    
assign_matrix *= cost_matrix

print('\nassign matrix\n',assign_matrix)

print('\nmax profit\n',assign_matrix.sum())

cost matrix 
 [[-2980.     -655.     -490.      -19.7     -19.97    -19.97 ]
 [-1989.5    -439.5    -329.5     -10.3     -10.48    -10.48 ]
 [-1485.     -322.5    -240.      -14.85    -14.985   -14.985]
 [ -993.5    -218.5    -163.5      -6.4      -6.49     -6.49 ]
 [-1982.5    -432.5    -322.5     -17.3     -17.48    -17.48 ]]

assign matrix
 [[-2980.       -0.       -0.       -0.       -0.       -0.   ]
 [   -0.     -439.5      -0.       -0.       -0.       -0.   ]
 [   -0.       -0.       -0.       -0.       -0.      -14.985]
 [   -0.       -0.       -0.       -0.       -6.49     -0.   ]
 [   -0.       -0.     -322.5      -0.       -0.       -0.   ]]

max profit
 -3763.4750000000004


In [142]:
# Worker={'pay': 20, 'rate': 300},   flower=orchid, profitability=   $2980/hour
# Worker={'pay': 10.5, 'rate': 200}, flower=daisy, profitability=    $439.5/hour
# Worker={'pay': 15, 'rate': 150},   flower=dandelion, profitability=$-14.85/hour
# Worker={'pay': 6.5, 'rate': 100},  flower=grass, profitability=    $-6.49/hour
# Worker={'pay': 17.5, 'rate': 200}, flower=daffodil, profitability= $322.5/hour

# Maximum Profit: $3720.6600000000003/hour

# Student Project Assignment

In [211]:
n_students = 10
n_projects = 15
n_choices = 5

def build_cost_matrix(n_students, n_projects):
    """
    Creates a 
    """
    students = list(range(n_students))
    projects = list(range(n_projects))

    cost_matrix = []
    for s in students:
        selection = [0 for p in projects] # student selection form
        
        # picks 5 ranked choices per student for projects selected randomly from a weighted probability distribution
        for n in range(1, n_choices+1):
            element = random.choices(np.arange(n_projects), weights=np.linspace(0, 1, n_projects))
            selection[element[0]]=0-n
            
        cost_matrix.append(selection)
    
    return np.array(cost_matrix)

In [212]:
cost_matrix = build_cost_matrix(n_students, n_projects)
print(cost_matrix)

[[ 0  0  0  0  0 -1  0 -2  0 -4  0  0 -3  0 -5]
 [ 0  0  0  0  0  0  0 -4  0  0 -1 -5 -3 -2  0]
 [ 0  0  0  0  0  0  0  0  0 -4  0  0  0 -5  0]
 [ 0  0  0  0  0  0  0  0 -3  0  0  0  0 -5 -4]
 [ 0 -3  0  0  0  0  0  0 -5 -1  0 -2  0  0  0]
 [ 0  0  0  0  0  0 -5 -4 -2 -3  0  0  0  0  0]
 [ 0  0  0  0  0  0 -4  0  0  0  0  0 -5 -2 -3]
 [ 0  0  0  0  0  0  0  0  0 -1  0 -4  0  0 -5]
 [ 0  0  0  0  0 -4  0  0 -2 -5  0 -1 -3  0  0]
 [ 0 -3  0  0  0  0  0  0  0 -1  0  0 -5 -4  0]]


In [213]:
studentID, projectID = linear_sum_assignment(cost_matrix)
#print(studentID, projectID)

In [214]:
cost_matrix.shape

(10, 15)

In [215]:
assign_matrix = np.zeros(cost_matrix.shape)

for s, p in zip(studentID, projectID):
    assign_matrix[s, p] = 1
    
assign_matrix *= cost_matrix

print('\nassign matrix\n',np.matrix(np.absolute(assign_matrix)))

print('\nmax profit\n', np.absolute(assign_matrix).sum())


assign matrix
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 5.]
 [0. 0. 0. 0. 0. 0. 0. 4. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 4. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 5. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 5. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 5. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 4. 0. 0. 0.]
 [0. 0. 0. 0. 0. 4. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 3. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

max profit
 44.0
