# Knapsack
Given a set of items, each with a weight and a value, determine the number of each item to include in a collection so that the total weight is less than or equal to a given limit and the total value is as large as possible.

In [3]:
import numpy as np

In [75]:
W = 10
v_ = [10, 40, 30, 50]
w_ = [5, 4, 6, 3]


def knapsack(v_, w_, W): 
    """
    v_ = values
    w_ = weights
    W = max weight
    """
    n = len(v_)
    
    V = np.zeros((n+1,W+1))
    keep = np.zeros((n+1,W+1))
    
#     for w in range(W+1):
#         V[0,w] = 0

    for i in range(1, n+1):
        for w in range(W+1):
            #print(i,w)
            
            # take item
            if w >= w_[i-1] and (v_[i-1] + V[i-1, w-w_[i-1]] > V[i-1,w]):
            
                V[i,w] = v_[i-1] + V[i-1, w-w_[i-1]]
                
                keep[i,w] = 1
                
            # leave item
            else:
                V[i,w] = V[i-1,w]

        
        
    return V, keep
        
    
    

In [76]:
V, keep = knapsack(v_, w_, W)
print(V)
print(keep)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. 10. 10. 10. 10. 10. 10.]
 [ 0.  0.  0.  0. 40. 40. 40. 40. 40. 50. 50.]
 [ 0.  0.  0.  0. 40. 40. 40. 40. 40. 50. 70.]
 [ 0.  0.  0. 50. 50. 50. 50. 90. 90. 90. 90.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [77]:
T = []

K = W

for i in range(n, -1, -1):
    if keep[i,K]==1:
        print(w_[i-1])
        K = K-w_[i-1]
        print(K)
        T.append(i)
        
print(T)

3
7
4
3
[4, 2]


In [ ]:
v_ = [60, 100, 120]
w_ = [10, 20, 30]
W = 50

# Subset 

Subset with maximum value without exceeding limit (special case of Knapsack)

In [120]:
def subset_sum(data, limit):
    
    cache = [None for _ in range(limit+1)]
    cache[0] = []
    
    for d in data:
        for i in range(limit - d, -1, -1):
            print(i, end=',')
            if cache[i] is not None:
                cache[i + d] = cache[i] + [d]
        print()
        
    return(cache)
                
                

In [119]:
data = [1, 2, 3, 4, 13, 3, 25, 20]
subset_sum(data, 50)



49,48,47,46,45,44,43,42,41,40,39,38,37,36,35,34,33,32,31,30,29,28,27,26,25,24,23,22,21,20,19,18,17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1,0,
48,47,46,45,44,43,42,41,40,39,38,37,36,35,34,33,32,31,30,29,28,27,26,25,24,23,22,21,20,19,18,17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1,0,
47,46,45,44,43,42,41,40,39,38,37,36,35,34,33,32,31,30,29,28,27,26,25,24,23,22,21,20,19,18,17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1,0,
46,45,44,43,42,41,40,39,38,37,36,35,34,33,32,31,30,29,28,27,26,25,24,23,22,21,20,19,18,17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1,0,
37,36,35,34,33,32,31,30,29,28,27,26,25,24,23,22,21,20,19,18,17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1,0,
47,46,45,44,43,42,41,40,39,38,37,36,35,34,33,32,31,30,29,28,27,26,25,24,23,22,21,20,19,18,17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1,0,
25,24,23,22,21,20,19,18,17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1,0,
30,29,28,27,26,25,24,23,22,21,20,19,18,17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1,0,


[[],
 [1],
 [2],
 [3],
 [1, 3],
 [2, 3],
 [3, 3],
 [4, 3],
 [1, 4, 3],
 [2, 4, 3],
 [3, 4, 3],
 [1, 3, 4, 3],
 [2, 3, 4, 3],
 [1, 2, 3, 4, 3],
 [1, 13],
 [2, 13],
 [13, 3],
 [1, 13, 3],
 [2, 13, 3],
 [3, 13, 3],
 [20],
 [1, 20],
 [2, 20],
 [3, 20],
 [1, 3, 20],
 [2, 3, 20],
 [3, 3, 20],
 [4, 3, 20],
 [1, 4, 3, 20],
 [2, 4, 3, 20],
 [3, 4, 3, 20],
 [1, 3, 4, 3, 20],
 [2, 3, 4, 3, 20],
 [1, 2, 3, 4, 3, 20],
 [1, 13, 20],
 [2, 13, 20],
 [13, 3, 20],
 [1, 13, 3, 20],
 [2, 13, 3, 20],
 [3, 13, 3, 20],
 [4, 13, 3, 20],
 [1, 4, 13, 3, 20],
 [2, 4, 13, 3, 20],
 [3, 4, 13, 3, 20],
 [1, 3, 4, 13, 3, 20],
 [25, 20],
 [1, 25, 20],
 [2, 25, 20],
 [3, 25, 20],
 [1, 3, 25, 20],
 [2, 3, 25, 20]]

# Subset sum 