In [10]:
import numpy as np


In [15]:
full_map = np.zeros(49).reshape(7, 7)
bots = np.zeros(25)
bots[:5] = 1
np.random.shuffle(bots)
full_map[1:6, 1:6] += bots.reshape(5, 5)
full_map

[[ 1.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


In [12]:
def new_kernel():
    kernel = np.zeros(9)
    kernel[np.random.randint(9)] += 1
    kernel[4] -= 1
    return kernel.reshape(3, 3)

In [31]:
test_kernel = new_kernel()
test_kernel

array([[ 0.,  0.,  0.],
       [ 0., -1.,  0.],
       [ 1.,  0.,  0.]])

In [206]:
m = np.where(full_map == 1) - np.array([[1], [1]])
m

array([[0, 3, 4, 4, 4],
       [0, 3, 0, 2, 3]])

In [258]:
kernels = np.zeros_like(full_map)

for i, j in zip(*m):
    kernels[i:i+3, j:j+3] += new_kernel()
kernels

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1., -1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0., -1.,  0.,  0.],
       [ 0.,  0.,  0.,  0., -1.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.]])

Find things in first column that are equal to 1, and basically undo the operation.

In [9]:
# First column
for w in np.where(kernels[:, 0] > 0)[0]:
    window = kernels[max(0, w-1):w+2, 1]
    window[np.random.choice(np.where(window == -1)[0])] += 1
    kernels[w, 0] = 0

# Last column
for w in np.where(kernels[:, -1] > 0)[0]:
    window = kernels[max(0, w-1):w+2, -2]
    window[np.random.choice(np.where(window == -1)[0])] += 1
    kernels[w, -1] = 0

kernels



NameError: name 'kernels' is not defined

NameError: name 'numpy' is not defined