In [3]:
import numpy as np

In [17]:
bot_sense_range = 1

In [18]:
bot_sense_window = np.zeros((2*bot_sense_range + 1)**2)
bot_sense_window

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [19]:
print(len(bot_sense_window)//2)

4


In [20]:
bot_sense_window[(len(bot_sense_window)//2)]=1
bot_sense_window

array([ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.])

In [23]:
np.reshape(bot_sense_window, (np.sqrt(len(bot_sense_window)), np.sqrt(len(bot_sense_window))))

/usr/lib/python3/dist-packages/numpy/core/fromnumeric.py:225: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  return reshape(newshape, order=order)


array([[ 0.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  0.]])

In [29]:
k=(bot_sense_window[0]).any
k


<function float64.any>